---
abstract: 'Add plugin support for the Perl debugger'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-Pluggable
provides:
  DB:
    file: lib/DB/Pluggable.pm
    version: 1.100851
  DB::Pluggable:
    file: lib/DB/Pluggable.pm
    version: 1.100851
  DB::Pluggable::BreakOnTestNumber:
    file: lib/DB/Pluggable/BreakOnTestNumber.pm
    version: 1.100851
  DB::Pluggable::Constants:
    file: lib/DB/Pluggable/Constants.pm
    version: 1.100851
  DB::Pluggable::Plugin:
    file: lib/DB/Pluggable/Plugin.pm
    version: 1.100851
  DB::Pluggable::TypeAhead:
    file: lib/DB/Pluggable/TypeAhead.pm
    version: 1.100851
requires:
  Carp: 0
  Data::Dumper: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Hook::LexWrap: 0
  Hook::Modular: 0
  Hook::Modular::Plugin: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.88
  YAML: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DB-Pluggable
  homepage: http://search.cpan.org/dist/DB-Pluggable/
  repository: http://github.com/hanekomu/DB-Pluggable
version: 1.100851
